from enum import StrEnum, auto

FICHE_MAX_DISTANCE = 100
TOCHT_MAX_DISTANCE = 60
WEIDE_MAX_DISTANCE = 100
GEBIED_MAX_DISTANCE = 50_000
SKIP_BASIS_DISTANCE = 50

TRACKER_FAR_AWAY_METERS = 1000
TRACKER_FORBIDDEN_AREA_AWAY_FROM_ROUTE_METERS = 50

SWITCH_TRACE_TEAMS = 'trace_teams'


class CheckpointLogType(StrEnum):
    AUTOMATED = auto()


class NotificationType(StrEnum):
    TRACKER_OFFLINE = auto()
    TRACKER_FAR_AWAY = auto()
    TRACKER_SOS = auto()
    TRACKER_LOW_BATTERY = auto()
    TRACKER_IN_FORBIDDEN_AREA = auto()
