# Generated by Django 5.0.1 on 2024-04-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
