# Generated by Django 5.0.1 on 2024-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_switch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
