version: "3.4"

services:
  linker:
    build:
      context: .
      target: backend
    command: gunicorn linker.wsgi -w 4 --bind 0.0.0.0:8000 --chdir=/app
    depends_on:
      - postgis
      - redis
    volumes:
      - ./simulation-data:/simulation-data:ro
      - upload-media:/media
    environment:
      - ALLOWED_HOSTS=link2.tijsb.be
      - CSRF_TRUSTED_ORIGINS=https://link2.tijsb.be
      - DATABASE_URL=postgis://root:pass@postgis:5432/linker
      - CACHE_URL=redis://redis:6379
      - SIMULATION_PATH=/simulation-data
      - DEBUG=False
      - MEDIA_ROOT=/media
    networks:
      - linker_net

  linker_celery:
    build:
      context: .
      target: backend
    command: celery -A linker worker -l INFO --concurrency=4
    depends_on:
      - postgis
      - redis
    volumes:
      - ./simulation-data:/simulation-data:ro
      - upload-media:/media
    environment:
      - ALLOWED_HOSTS=link2.tijsb.be
      - CSRF_TRUSTED_ORIGINS=https://link2.tijsb.be
      - DATABASE_URL=postgis://root:pass@postgis:5432/linker
      - CACHE_URL=redis://redis:6379
      - SIMULATION_PATH=/simulation-data
      - DEBUG=False
      - MEDIA_ROOT=/media
    networks:
      - linker_net

  linker_celery_beat:
    build:
      context: .
      target: backend
    command: celery -A linker beat -l INFO
    depends_on:
      - postgis
      - redis
    volumes:
      - ./simulation-data:/simulation-data:ro
      - upload-media:/media
    environment:
      - ALLOWED_HOSTS=link2.tijsb.be
      - CSRF_TRUSTED_ORIGINS=https://link2.tijsb.be
      - DATABASE_URL=postgis://root:pass@postgis:5432/linker
      - CACHE_URL=redis://redis:6379
      - SIMULATION_PATH=/simulation-data
      - DEBUG=False
      - MEDIA_ROOT=/media
    networks:
      - linker_net

  postgis:
    image: kartoza/postgis:17-3.5
    environment:
      - POSTGRES_DB=linker
      - POSTGRES_USER=root
      - POSTGRES_PASS=pass
    volumes:
      - postgis-data:/var/lib/postgresql
    networks:
      - linker_net

  redis:
    image: redis:6
    networks:
      - linker_net

  tiles:
    image: ghcr.io/maplibre/martin
    volumes:
      - ./map_data:/map_data:ro
    command: '--config /map_data/martin.yaml'

  nginx:
    build:
      context: .
      target: custom-nginx
    networks:
      - linker_net
      - caddy
    volumes:
      - upload-media:/media
    depends_on:
      - linker
      - tiles
    labels:
      caddy: link2.tijsb.be
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  postgis-data:
  upload-media:

networks:
  caddy:
    external: true
  linker_net:
