services:
  linker:
    build:
      context: .
      target: backend
    command: python manage.py runserver 0.0.0.0:8060
    depends_on:
      - postgis
      - redis
    volumes:
      - ./simulation-data:/simulation-data:ro
      - ./backend:/app
      - ./media:/media
      - /app/.venv
    environment:
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgis://root:pass@postgis:5432/linker
      - CACHE_URL=redis://redis:6379
      - SIMULATION_PATH=/simulation-data
      - DEBUG=True
      - MEDIA_ROOT=/media
      - SECRET_KEY=secret
    ports:
      - "8060:8060"

  linker_celery:
    build:
      context: .
      target: backend
    command: watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- celery -A linker worker -B -l INFO
    depends_on:
      - postgis
      - redis
    volumes:
      - ./simulation-data:/simulation-data:ro
      - ./backend:/app
    environment:
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgis://root:pass@postgis:5432/linker
      - CACHE_URL=redis://redis:6379
      - SIMULATION_PATH=/simulation-data
      - DEBUG=True
      - MEDIA_ROOT=/media
      - SECRET_KEY=secret

  postgis:
    image: kartoza/postgis:17-3.5
    environment:
      - POSTGRES_DB=linker
      - POSTGRES_USER=root
      - POSTGRES_PASS=pass
    ports:
      - "8062:5432"
    volumes:
      - postgis-data:/var/lib/postgresql

  redis:
    image: redis:6
    ports:
      - "8063:6379"

  frontend:
    build:
      context: .
      target: frontend-dev
    command: npm run dev -- --port 8061 --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules/
      - /app/public/tiles/
    environment:
      - VITE_BACKEND_URL=http://linker:8060
      - VITE_TILES_URL=http://tiles:8064
    ports:
      - "8061:8061"

  tiles:
    image: ghcr.io/maplibre/martin
    volumes:
      - ./map_data:/map_data:ro
    command: '--config /map_data/martin.yaml'
    ports:
      - '8064:8064'

volumes:
  postgis-data:
