# Generated by Django 5.0 on 2024-01-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocht',
            name='leads',
            field=models.ManyToManyField(to='people.organizationmember'),
        ),
        migrations.AddField(
            model_name='fiche',
            name='tocht',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.tocht'),
        ),
        migrations.AddField(
            model_name='weide',
            name='tocht',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.tocht'),
        ),
        migrations.AlterUniqueTogether(
            name='fiche',
            unique_together={('order', 'tocht')},
        ),
    ]
