# Generated by Django 5.0.1 on 2024-02-08 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocht',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
