# Generated by Django 5.0.1 on 2024-04-23 18:28

import django.db.models.deletion
from django.db import migrations, models


mapping = {
    'A': 'Alpha',
    'B': 'Bravo',
    'C': 'Charlie',
    'D': 'Delta',
    'E': 'Echo',
    'F': 'Foxtrot',
}


def fill_in_data(apps, schema_editor):
    Weide = apps.get_model('map', 'Weide')
    for weide in Weide.objects.using(schema_editor.connection.alias).all():
        weide.identifier = weide.tocht.identifier
        weide.name = mapping[weide.tocht.identifier]
        weide.save()


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_mapnote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='weide',
            name='identifier',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='weide',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='weide',
            name='tocht',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.tocht'),
        ),
        migrations.RunPython(fill_in_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='weide',
            name='identifier',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='weide',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
