# Generated by Django 5.1.6 on 2025-04-16 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_weide_tocht'),
        ('people', '0009_team_safe_weide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocht',
            name='is_alternative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tocht',
            name='identifier',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='tocht',
            name='leads',
            field=models.ManyToManyField(blank=True, to='people.organizationmember'),
        ),
        migrations.AlterField(
            model_name='tocht',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
