# Generated by Django 6.0.4 on 2026-04-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_forbiddenarea_route_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='weide',
            name='slotweide',
            field=models.BooleanField(default=False),
        ),
    ]
