# Generated by Django 5.0 on 2024-01-28 13:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.CharField(db_index=True, max_length=50)),
                ('tracker_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_datetime', models.DateTimeField(db_index=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fetch_datetime', models.DateTimeField(db_index=True)),
                ('local_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_sync_date', models.DateTimeField(blank=True, null=True)),
                ('satellites', models.IntegerField(blank=True, null=True)),
                ('input_acc', models.BooleanField(blank=True, null=True)),
                ('voltage', models.CharField(blank=True, max_length=30, null=True)),
                ('analog_input', models.FloatField(blank=True, null=True)),
                ('tracker_type', models.IntegerField(blank=True, null=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('is_online', models.BooleanField(blank=True, null=True)),
                ('has_gps', models.BooleanField(blank=True, null=True)),
                ('has_power', models.BooleanField(blank=True, null=True)),
                ('is_online_threshold', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_logs', to='trackers.tracker')),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='last_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trackers.trackerlog'),
        ),
    ]
