# Generated by Django 5.0 on 2024-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='tracker_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='trackerlog',
            unique_together={('tracker', 'gps_datetime')},
        ),
    ]
