# Generated by Django 5.0.1 on 2024-04-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_alter_tracker_tracker_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerlog',
            name='team_is_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trackerlog',
            name='fetch_datetime',
            field=models.DateTimeField(),
        ),
    ]
