# Generated by Django 5.0.1 on 2024-04-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_trackerlog_team_is_safe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='tracker_code',
            new_name='tracker_name',
        ),
    ]
