# Generated by Django 5.0.1 on 2024-05-24 21:56

import enumfields.fields
from django.db.models import Case, When, Value

import linker.trackers.constants
from django.db import migrations, models

def update_trackerlog_source(apps, schema_editor):
    TrackerLog = apps.get_model('trackers', 'TrackerLog')
    db_alias = schema_editor.connection.alias
    TrackerLog.objects.using(db_alias).filter(fetch_datetime__isnull=True).update(source='minisite_api')
    TrackerLog.objects.using(db_alias).filter(fetch_datetime__isnull=False).update(source='geodynamics_api')


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_alter_trackerlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerlog',
            name='source',
            field=enumfields.fields.EnumField(blank=True, enum=linker.trackers.constants.TrackerLogSource, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trackerlog',
            name='tracker_type',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(update_trackerlog_source, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trackerlog',
            name='source',
            field=enumfields.fields.EnumField(enum=linker.trackers.constants.TrackerLogSource, max_length=30),
        ),
    ]
