# Generated by Django 6.0.4 on 2026-04-22 08:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import enumfields.fields
import linker.trackers.constants
from django.db import migrations, models

def copy_trackerlogs_to_positions(apps, schema_editor):
    # Pure SQL copy — avoids all ORM field conversion issues (enumfields rejects
    # 'manual' on read, GIS proxy rejects raw bytes on write). The DB copies the
    # geometry column directly without passing through Python.
    schema_editor.execute("""
        INSERT INTO trackers_position (team_id, organization_member_id, timestamp, point, source)
        SELECT t.id, NULL, tl.gps_datetime, tl.point, tl.source
        FROM trackers_trackerlog tl
        JOIN people_team t ON t.tracker_id = tl.tracker_id

        UNION ALL

        SELECT NULL, o.id, tl.gps_datetime, tl.point, tl.source
        FROM trackers_trackerlog tl
        JOIN people_organizationmember o ON o.tracker_id = tl.tracker_id
    """)

    schema_editor.execute("DELETE FROM trackers_trackerlog WHERE source = 'manual'")


def reverse_copy_trackerlogs_to_positions(apps, schema_editor):
    # Recreate manual TrackerLog rows from Position rows using raw SQL,
    # because TrackerLogSource no longer has 'manual' so ORM writes would fail.
    schema_editor.execute("""
        INSERT INTO trackers_trackerlog (tracker_id, gps_datetime, point, source, team_is_safe)
        SELECT
            COALESCE(t.tracker_id, o.tracker_id),
            p.timestamp,
            p.point,
            'manual',
            false
        FROM trackers_position p
        LEFT JOIN people_team t ON t.id = p.team_id
        LEFT JOIN people_organizationmember o ON o.id = p.organization_member_id
        WHERE p.source = 'manual'
          AND COALESCE(t.tracker_id, o.tracker_id) IS NOT NULL
        ON CONFLICT DO NOTHING
    """)

    schema_editor.execute("DELETE FROM trackers_position")


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_add_login_token'),
        ('trackers', '0007_alter_tracker_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='last_log',
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('source', enumfields.fields.EnumField(enum=linker.trackers.constants.PositionSource, max_length=30)),
                ('organization_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='people.organizationmember')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='people.team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'timestamp'], name='trackers_po_team_id_296f1a_idx'), models.Index(fields=['organization_member', 'timestamp'], name='trackers_po_organiz_b1002f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization_member__isnull', True), ('team__isnull', False)), models.Q(('organization_member__isnull', False), ('team__isnull', True)), _connector='OR'), name='position_exactly_one_owner')],
            },
        ),
        migrations.RunPython(copy_trackerlogs_to_positions, reverse_copy_trackerlogs_to_positions),
    ]
