# Generated by Django 6.0.4 on 2026-04-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0008_remove_tracker_last_log_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerlog',
            name='team_is_safe',
        ),
    ]
