# Generated by Django 6.0.4 on 2026-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0009_remove_trackerlog_team_is_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='tracker_barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
