# Generated by Django 6.0.4 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0011_remove_duplicate_positions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(
                fields=['timestamp', 'source', 'team', 'organization_member'],
                name='position_unique_timestamp_source_owner',
            ),
        ),
    ]
