# Generated by Django 6.0.4 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0012_position_unique_timestamp_source_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='position_unique_timestamp_source_owner',
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(
                fields=['timestamp', 'source', 'team', 'organization_member'],
                name='position_unique_timestamp_source_owner',
                nulls_distinct=False,
            ),
        ),
    ]
