# Generated by Django 5.0 on 2024-01-28 13:51

import django.db.models.deletion
import enumfields.fields
import linker.people.constants
import linker.people.models
from django.db import migrations, models



def group_picture_path(instance, filename):
    return f'G{instance.number:02d}_{filename}'


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
                ('member_type', enumfields.fields.EnumField(enum=linker.people.constants.MemberType, max_length=13)),
                ('tracker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackers.tracker')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', enumfields.fields.EnumField(enum=linker.people.constants.Direction, max_length=10)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('chiro', models.CharField(max_length=100)),
                ('group_picture', models.ImageField(upload_to=group_picture_path)),
                ('eind_weide_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='map.weide')),
                ('eind_weide_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='map.weide')),
                ('start_weide_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='map.weide')),
                ('start_weide_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='map.weide')),
                ('tracker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackers.tracker')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='people.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_notes', to='people.team')),
            ],
        ),
    ]
