# Generated by Django 5.0.1 on 2024-02-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='is_leader',
            new_name='is_favorite',
        ),
    ]
