# Generated by Django 5.0.1 on 2024-03-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_forbiddenarea'),
        ('people', '0002_rename_is_leader_contactperson_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='safe_weide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_teams', to='map.weide'),
        ),
    ]
