# Generated by Django 5.0.1 on 2024-03-07 13:00

import linker.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_team_safe_weide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group_picture',
            field=models.ImageField(blank=True, null=True, upload_to=linker.people.models.group_picture_path),
        ),
    ]
