# Generated by Django 5.0.1 on 2024-04-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_team_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='eind_weide_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='eind_weide_2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='start_weide_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='start_weide_2',
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='code',
            field=models.CharField(help_text='De letters die op de kaart verschijnen', max_length=5),
        ),
    ]
