# Generated by Django 5.1.6 on 2025-04-15 21:40

from django.db import migrations, models


def safe_weide_to_name(apps, schema_editor):
    Team = apps.get_model('people', 'Team')
    for team in Team.objects.all().select_related('safe_weide'):
        team.safe_weide_name = team.safe_weide.name
        team.save()


def name_to_safe_weide(apps, schema_editor):
    Team = apps.get_model('people', 'Team')
    Weide = apps.get_model('map', 'Weide')
    for team in Team.objects.all():
        team.safe_weide = Weide.objects.filter(name=team.safe_weide_name).first()
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_team_safe_weide_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='safe_weide_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(safe_weide_to_name, reverse_code=name_to_safe_weide),
        migrations.RemoveField(
            model_name='team',
            name='safe_weide',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='safe_weide_name',
            new_name='safe_weide',
        ),
    ]
