# Generated by Django 5.2 on 2025-05-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_team_safe_weide_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('can_upload_picture', 'Can upload a group picture'), ('view_stats', 'Can view team stats')]},
        ),
    ]
