# Generated by Django 5.1.6 on 2025-04-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_team_safe_weide_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('can_upload_picture', 'Can upload a group picture'), ('can_see_tracing', 'Can see tracing information')]},
        ),
    ]
