# Generated by Django 5.2 on 2025-05-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('view_stats', 'Can view team stats')]},
        ),
        migrations.RemoveField(
            model_name='team',
            name='group_picture',
        ),
    ]
