# Generated by Django 5.2.3 on 2025-06-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_alter_team_options_remove_team_group_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': [('view_stats', 'Can view team stats'), ('view_all_teams', 'Can view all teams'), ('view_team_details', 'Can view team details'), ('view_team_number', 'Can view team number')]},
        ),
    ]
