# Generated by Django 6.0.4 on 2026-04-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_add_login_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='safe_weide',
        ),
        migrations.RemoveField(
            model_name='team',
            name='safe_weide_updated_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='safe_weide_updated_by',
        ),
        migrations.CreateModel(
            name='TeamSafetyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_safety_logs', to='people.team')),
            ],
        ),
    ]
