# Generated by Django 6.0.4 on 2026-04-22 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_remove_team_safe_weide_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teamsafetylog',
            index=models.Index(fields=['team', '-created'], name='people_team_team_id_01e669_idx'),
        ),
    ]
