# Generated by Django 6.0.4 on 2026-05-13 06:08

from django.db import migrations, models
from secrets import token_urlsafe


def add_random_tracker_tokens(apps, schema_editor):
    Team = apps.get_model('people', 'Team')
    teams = list(Team.objects.all())
    for team in teams:
        team.tracker_token = token_urlsafe(32)
    Team.objects.bulk_update(teams, ['tracker_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_teamsafetylog_people_team_team_id_01e669_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tracker_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(add_random_tracker_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='team',
            name='tracker_token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
