# Generated by Django 6.0.4 on 2026-06-28

from django.db import migrations, models
from secrets import token_urlsafe
import linker.people.models


def add_random_tracker_tokens(apps, schema_editor):
    OrganizationMember = apps.get_model('people', 'OrganizationMember')
    members = list(OrganizationMember.objects.all())
    for member in members:
        member.tracker_token = token_urlsafe(32)
    OrganizationMember.objects.bulk_update(members, ['tracker_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_team_tracker_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='tracker_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(add_random_tracker_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organizationmember',
            name='tracker_token',
            field=models.CharField(default=linker.people.models._default_tracker_token, max_length=64, unique=True),
        ),
    ]
