# Generated by Django 5.0 on 2024-01-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived', models.DateTimeField()),
                ('left', models.DateTimeField()),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.fiche')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpointlogs', to='people.team')),
            ],
        ),
    ]
