# Generated by Django 5.0 on 2024-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointlog',
            name='left',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
