# Generated by Django 5.1.6 on 2025-03-18 21:57

import django.db.models.deletion
import enumfields.fields
import linker.tracing.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0002_alter_checkpointlog_left'),
        ('trackers', '0006_trackerlog_source_alter_trackerlog_tracker_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', enumfields.fields.EnumField(enum=linker.tracing.constants.NotificationType, max_length=255)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('severity', models.IntegerField(default=0)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackers.tracker')),
            ],
        ),
        migrations.CreateModel(
            name='ReadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracing.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'notification'), name='unique_user_notification')],
            },
        ),
    ]
