# Generated by Django 6.0.4 on 2026-04-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_add_login_token'),
        ('tracing', '0003_notification_readnotification'),
        ('trackers', '0008_remove_tracker_last_log_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.team'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackers.tracker'),
        ),
    ]
